version: 2
jobs:
  build:
    docker: [{image: "circleci/node:lts"}]
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-{{ checksum "package-lock.json" }}
            - dependencies-
      - run: npm ci
      - save_cache:
          paths: [node_modules]
          key: dependencies-{{ checksum "package-lock.json" }}
      # - run: npm run build
      - run: git diff --exit-code
      - persist_to_workspace: {root: ., paths: [.]}
  test:
    docker: [{image: "circleci/node:lts"}]
    steps:
      - attach_workspace: {at: .}
      - run: sudo npm install -g nyc codecov
      - run: nyc npx test
      - run: codecov
  lint:
    docker: [{image: "circleci/node:lts"}]
    steps:
      - attach_workspace: {at: .}
      - run: npm run lint
  deploy:
    docker: [{image: "circleci/node:lts"}]
    steps:
      - attach_workspace:
          at: .
      - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
      - run: npx lerna publish from-package --no-git-reset --yes
  onBranch:
    docker: [{image: "circleci/node:lts"}]
    steps:
      - run: if [[ -z $CIRCLE_BRANCH ]]; then exit 1; fi
  isTagged:
    docker: [{image: "circleci/node:lts"}]
    steps:
      - run: if [[ -z $CIRCLE_TAG ]]; then exit 1; fi
workflows:
  version: 2
  run-tests:
    jobs:
      - onBranch:
          filters:
            branches: {ignore: master}
            tags: {ignore: /.*/}
      - build: {requires: [onBranch]}
      - test: {requires: [build]}
      - lint: {requires: [build]}
  release:
    jobs:
      - isTagged:
          filters:
            branches: {ignore: /.*/}
            tags: {only: /^v.*/}
      - build:
          requires: [isTagged]
          filters:
            branches: {ignore: /.*/}
            tags: {only: /^v.*/}
      - test:
          requires: [build]
          filters:
            branches: {ignore: /.*/}
            tags: {only: /^v.*/}
      - lint:
          requires: [build]
          filters:
            branches: {ignore: /.*/}
            tags: {only: /^v.*/}
      - deploy:
          requires: [test, lint]
          filters:
            branches: {ignore: /.*/}
            tags: {only: /^v.*/}
